### ISSUE TITLE
Will the code have license?

### ISSUE THREAD

**Issue by pseudoge** [tabayashi0117/Score-CAM#25]
Hello. I like the clean implementation of yours. Currently there is no license for the repository. Would you kindly add one, for the community to modify and reuse the code?

**Comment by tabayashi0117** [comment]
@pseudoge 
Thank you for contacting me. The license file has just been added.

**Comment by pseudoge** [comment]
@tabayashi0117 Thank you very much for your prompt reply, and for adding the license.
